### ISSUE TITLE
If we receive node updates, we must create missing DB entries

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-python#2]

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/3-device-mesh-error-on-device-connected-via-usb/450/2

**Comment by nicetechguy** [comment]
Error at end of log appears when second node is powered on in range.
Just a guess..Could this be due to each device being upgraded/reflashed one at a time from 0.7.4 to 0.7.5 and not being recongised correctly even though it had the same ID?

[log-error-meshtastic-202006180839.txt](https://github.com/meshtastic/Meshtastic-python/files/4795388/log-error-meshtastic-202006180839.txt)

**Comment by geeksville** [comment]
oh thanks!  No it is a bug in the python library.  It is the libaries responsibility to update the nodedb when new nodes show up and it isn't doing that I'll fix now.

**Comment by geeksville** [comment]
Thank you for the report @nicetechguy.  Fixed in 0.7.5 just released to pypi.

**Comment by nicetechguy** [comment]
Thank you for the prompt assist!

Excited to see how this project progresses going forwards - hoping it will be the best fit for our use case :)

**Comment by nicetechguy** [comment]
updated just now and encountering another error:

[log-error-meshtastic-202006181030.txt](https://github.com/meshtastic/Meshtastic-python/files/4795647/log-error-meshtastic-202006181030.txt)

**Comment by nicetechguy** [comment]
Looks good now on 0.7.6 - thanks :)
